global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#aleksandr_zakharov'
